package ISIS.Code.Class;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.event.EventListenerList;

import ISIS.Code.Matriz.Construccion;
import ISIS.Code.Matriz.Estados;
import ISIS.Code.Matriz.ImageCache;
import ISIS.Code.Matriz.Mapa;
import ISIS.Code.Panels.GamePanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Jose
 */
public class DialogoIndustria extends javax.swing.JDialog {

	/**
	 * Creates new form Dialogo
	 */
	public DialogoIndustria(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		System.out.println("incia componentes dialogo");
		panelNice1 = new org.edisoncor.gui.panel.PanelNice();
		tabbedSelector21 = new org.edisoncor.gui.tabbedPane.TabbedSelector2();
		panelImage1 = new org.edisoncor.gui.panel.PanelImage();
		panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
		buttonComprar1 = new org.edisoncor.gui.button.ButtonSeven();
		buttonComprar2 = new org.edisoncor.gui.button.ButtonSeven();
		buttonComprar3 = new org.edisoncor.gui.button.ButtonSeven();
		buttonComprar4 = new org.edisoncor.gui.button.ButtonSeven();
		buttonComprar5 = new org.edisoncor.gui.button.ButtonSeven();
		lblEdif1 = new javax.swing.JLabel();
		lblEdif2 = new javax.swing.JLabel();
		lblEdif3 = new javax.swing.JLabel();
		lblEdif4 = new javax.swing.JLabel();
		lblEdif5 = new javax.swing.JLabel();

		buttonSeven26 = new org.edisoncor.gui.button.ButtonSeven();
		panelImage2 = new org.edisoncor.gui.panel.PanelImage();
		panelCurves4 = new org.edisoncor.gui.panel.PanelCurves();
		jLabel6 = new javax.swing.JLabel();
		buttonSeven6 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel7 = new javax.swing.JLabel();
		buttonSeven7 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel8 = new javax.swing.JLabel();
		buttonSeven8 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel9 = new javax.swing.JLabel();
		buttonSeven9 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel10 = new javax.swing.JLabel();
		buttonSeven10 = new org.edisoncor.gui.button.ButtonSeven();
		buttonSeven27 = new org.edisoncor.gui.button.ButtonSeven();
		panelImage3 = new org.edisoncor.gui.panel.PanelImage();
		panelCurves5 = new org.edisoncor.gui.panel.PanelCurves();
		jLabel11 = new javax.swing.JLabel();
		buttonSeven11 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel12 = new javax.swing.JLabel();
		buttonSeven12 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel13 = new javax.swing.JLabel();
		buttonSeven13 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel14 = new javax.swing.JLabel();
		buttonSeven14 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel15 = new javax.swing.JLabel();
		buttonSeven15 = new org.edisoncor.gui.button.ButtonSeven();
		buttonSeven28 = new org.edisoncor.gui.button.ButtonSeven();
		panelImage4 = new org.edisoncor.gui.panel.PanelImage();
		panelCurves2 = new org.edisoncor.gui.panel.PanelCurves();
		jLabel16 = new javax.swing.JLabel();
		buttonSeven16 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel17 = new javax.swing.JLabel();
		buttonSeven17 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel18 = new javax.swing.JLabel();
		buttonSeven18 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel19 = new javax.swing.JLabel();
		buttonSeven19 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel20 = new javax.swing.JLabel();
		buttonSeven20 = new org.edisoncor.gui.button.ButtonSeven();
		buttonSeven29 = new org.edisoncor.gui.button.ButtonSeven();
		panelImage5 = new org.edisoncor.gui.panel.PanelImage();
		panelCurves3 = new org.edisoncor.gui.panel.PanelCurves();
		jLabel21 = new javax.swing.JLabel();
		buttonSeven21 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel22 = new javax.swing.JLabel();
		buttonSeven22 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel23 = new javax.swing.JLabel();
		buttonSeven23 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel24 = new javax.swing.JLabel();
		buttonSeven24 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel25 = new javax.swing.JLabel();
		buttonSeven25 = new org.edisoncor.gui.button.ButtonSeven();
		buttonSeven30 = new org.edisoncor.gui.button.ButtonSeven();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setUndecorated(true);

		panelNice1.setPreferredSize(new java.awt.Dimension(500, 400));

		panelImage1.setIcon(new javax.swing.ImageIcon(ImageCache.getInstance()
				.getImage("src/ISIS/Resource/Backgrounds/BackCasas.jpg")));

		panelImage1.setLayout(null);

		panelCurves1.setLayout(null);

		// Edificacion 1 Nivel 1
		buttonComprar1.setBackground(new java.awt.Color(255, 0, 0));
		buttonComprar1.setText("Comprar");
		panelCurves1.add(buttonComprar1);
		buttonComprar1.setBounds(100, 100, 70, 22);
		buttonComprar1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("carpinteria");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});
		lblEdif1.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 1/lblCarpinteria.png")));
		panelCurves1.add(lblEdif1);
		lblEdif1.setBounds(27, 12, 189, 100);

		// Edificacion 2 Nivel 1
		lblEdif2.setBounds(30, 130, 189, 100);
		buttonComprar2.setBackground(new java.awt.Color(255, 0, 0));
		buttonComprar2.setText("Comprar");
		panelCurves1.add(buttonComprar2);
		buttonComprar2.setBounds(110, 220, 70, 22);
		buttonComprar2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("cafeteria");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});
		lblEdif2.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 1/lblCafeteria.png")));
		panelCurves1.add(lblEdif2);

		// Edificacion 3 Nivel 1
		lblEdif3.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 1/lblAlmuerzoPopular.png")));
		panelCurves1.add(lblEdif3);
		lblEdif3.setBounds(30, 260, 189, 100);

		buttonComprar3.setBackground(new java.awt.Color(255, 0, 0));
		buttonComprar3.setText("Comprar");
		panelCurves1.add(buttonComprar3);
		buttonComprar3.setBounds(110, 350, 70, 22);
		buttonComprar3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("almuerzoPopular");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		lblEdif4.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 1/lblMercal.png")));
		panelCurves1.add(lblEdif4);
		lblEdif4.setBounds(220, 70, 189, 100);

		buttonComprar4.setBackground(new java.awt.Color(255, 0, 0));
		buttonComprar4.setText("Comprar");
		panelCurves1.add(buttonComprar4);
		buttonComprar4.setBounds(300, 160, 70, 22);
		buttonComprar4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("mercal");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		lblEdif5.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 1/lblLicoreria.png")));
		panelCurves1.add(lblEdif5);
		lblEdif5.setBounds(220, 200, 189, 100);

		buttonComprar5.setBackground(new java.awt.Color(255, 0, 0));
		buttonComprar5.setText("Comprar");
		panelCurves1.add(buttonComprar5);
		buttonComprar5.setBounds(300, 290, 70, 22);
		buttonComprar5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("licoreria");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		buttonSeven26.setBackground(new java.awt.Color(0, 0, 255));
		buttonSeven26.setText("Volver");
		buttonSeven26.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
			}
		});
		panelCurves1.add(buttonSeven26);
		buttonSeven26.setBounds(406, 345, 80, 30);
		panelImage1.add(panelCurves1);
		panelCurves1.setBounds(-1, -1, 490, 390);

		tabbedSelector21.addTab("", new javax.swing.ImageIcon(getClass()
				.getResource("/ISIS/Resource/ButtonImages/#1 (Copiar).png")),
				panelImage1, ""); // NOI18N

		panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ISIS/Resource/Backgrounds/BackCasas2.jpg"))); // NOI18N
		panelImage2.setLayout(null);

		panelCurves4.setLayout(null);

		jLabel6.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 2/lblabasto.png")));
		panelCurves4.add(jLabel6);
		jLabel6.setBounds(27, 12, 189, 100);

		buttonSeven6.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven6.setText("Comprar");
		panelCurves4.add(buttonSeven6);
		buttonSeven6.setBounds(100, 100, 70, 22);
		buttonSeven6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("abasto");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel7.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 2/lblbanco.png")));
		panelCurves4.add(jLabel7);
		jLabel7.setBounds(30, 130, 189, 100);

		buttonSeven7.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven7.setText("Comprar");
		panelCurves4.add(buttonSeven7);
		buttonSeven7.setBounds(110, 220, 70, 22);
		buttonSeven7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("banco");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel8.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 2/lblfarmacia.png")));
		panelCurves4.add(jLabel8);
		jLabel8.setBounds(30, 260, 189, 100);

		buttonSeven8.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven8.setText("Comprar");
		panelCurves4.add(buttonSeven8);
		buttonSeven8.setBounds(110, 350, 70, 22);
		buttonSeven8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("farmacia");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel9.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 2/lblpanaderia.png")));
		panelCurves4.add(jLabel9);
		jLabel9.setBounds(220, 12, 189, 100);

		buttonSeven9.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven9.setText("Comprar");
		panelCurves4.add(buttonSeven9);
		buttonSeven9.setBounds(300, 100, 70, 22);
		buttonSeven9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("panaderia");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel10.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 2/lblrestaurante.png")));
		panelCurves4.add(jLabel10);
		jLabel10.setBounds(220, 130, 189, 100);

		buttonSeven10.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven10.setText("Comprar");
		panelCurves4.add(buttonSeven10);
		buttonSeven10.setBounds(300, 220, 70, 22);
		buttonSeven10.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("restaurante");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		buttonSeven27.setBackground(new java.awt.Color(0, 0, 255));
		buttonSeven27.setText("Volver");
		buttonSeven27.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
			}
		});
		panelCurves4.add(buttonSeven27);
		buttonSeven27.setBounds(406, 345, 80, 30);

		panelImage2.add(panelCurves4);
		panelCurves4.setBounds(0, 0, 490, 390);

		tabbedSelector21.addTab("", new javax.swing.ImageIcon(getClass()
				.getResource("/ISIS/Resource/ButtonImages/#2 (Copiar).png")),
				panelImage2); // NOI18N
		panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ISIS/Resource/Backgrounds/BackCasas3.jpg"))); // NOI18N
		panelImage3.setLayout(null);

		panelCurves5.setLayout(null);

		jLabel11.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 3/lblcomplejoTuristico.png")));
		panelCurves5.add(jLabel11);
		jLabel11.setBounds(27, 12, 189, 100);

		buttonSeven11.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven11.setText("Comprar");
		panelCurves5.add(buttonSeven11);
		buttonSeven11.setBounds(100, 100, 70, 22);
		buttonSeven11.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("complejoTuristico");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel12.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 3/lblferiaComida.png")));
		panelCurves5.add(jLabel12);
		jLabel12.setBounds(30, 130, 189, 100);

		buttonSeven12.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven12.setText("Comprar");
		panelCurves5.add(buttonSeven12);
		buttonSeven12.setBounds(110, 220, 70, 22);
		buttonSeven12.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("feriaComida");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel13.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 3/lblgimnasio.png")));
		panelCurves5.add(jLabel13);
		jLabel13.setBounds(30, 260, 189, 100);

		buttonSeven13.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven13.setText("Comprar");
		panelCurves5.add(buttonSeven13);
		buttonSeven13.setBounds(110, 350, 70, 22);
		buttonSeven13.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("gimnasio");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel14.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 3/lblmcDonalds.png")));
		panelCurves5.add(jLabel14);
		jLabel14.setBounds(220, 70, 189, 100);

		buttonSeven14.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven14.setText("Comprar");
		panelCurves5.add(buttonSeven14);
		buttonSeven14.setBounds(300, 160, 70, 22);
		buttonSeven14.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("mcDonalds");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel15.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 3/lbloficinas.png")));
		panelCurves5.add(jLabel15);
		jLabel15.setBounds(220, 200, 189, 100);

		buttonSeven15.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven15.setText("Comprar");
		panelCurves5.add(buttonSeven15);
		buttonSeven15.setBounds(300, 290, 70, 22);
		buttonSeven15.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("oficinas");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		buttonSeven28.setBackground(new java.awt.Color(0, 0, 255));
		buttonSeven28.setText("Volver");
		buttonSeven28.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
			}
		});
		panelCurves5.add(buttonSeven28);
		buttonSeven28.setBounds(406, 345, 80, 30);

		panelImage3.add(panelCurves5);
		panelCurves5.setBounds(0, 0, 490, 390);

		tabbedSelector21.addTab("", new javax.swing.ImageIcon(getClass()
				.getResource("/ISIS/Resource/ButtonImages/#3 (Copiar).png")),
				panelImage3); // NOI18N

		panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ISIS/Resource/Backgrounds/BackCasas4.jpg"))); // NOI18N
		panelImage4.setLayout(null);

		panelCurves2.setLayout(null);

		jLabel16.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 4/lblcentroComercial.png")));
		panelCurves2.add(jLabel16);
		jLabel16.setBounds(27, 12, 189, 100);

		buttonSeven16.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven16.setText("Comprar");
		panelCurves2.add(buttonSeven16);
		buttonSeven16.setBounds(100, 100, 70, 22);
		buttonSeven16.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("centroComercial");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel17.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 4/lbldiscoteca.png")));
		panelCurves2.add(jLabel17);
		jLabel17.setBounds(30, 130, 189, 100);

		buttonSeven17.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven17.setText("Comprar");
		panelCurves2.add(buttonSeven17);
		buttonSeven17.setBounds(110, 220, 70, 22);
		buttonSeven17.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("discoteca");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel18.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 4/lblsuperMercado.png")));
		panelCurves2.add(jLabel18);
		jLabel18.setBounds(30, 260, 189, 100);

		buttonSeven18.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven18.setText("Comprar");
		panelCurves2.add(buttonSeven18);
		buttonSeven18.setBounds(110, 350, 70, 22);
		buttonSeven18.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("superMercado");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel19.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 4/lbltiendaMusical.png")));
		panelCurves2.add(jLabel19);
		jLabel19.setBounds(220, 70, 189, 100);

		buttonSeven19.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven19.setText("Comprar");
		panelCurves2.add(buttonSeven19);
		buttonSeven19.setBounds(300, 160, 70, 22);
		buttonSeven19.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("tiendaMusical");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		// jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource(
		// "/ISIS/Resource/ButtonImages/PetroCasa.png"))); // NOI18N
		// panelCurves2.add(jLabel20);
		// jLabel20.setBounds(220, 200, 189, 100);
		//
		// buttonSeven20.setBackground(new java.awt.Color(255, 0, 0));
		// buttonSeven20.setText("Comprar");
		// panelCurves2.add(buttonSeven20);
		// buttonSeven20.setBounds(300, 290, 70, 22);

		buttonSeven29.setBackground(new java.awt.Color(0, 0, 255));
		buttonSeven29.setText("Volver");
		buttonSeven29.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
			}
		});
		panelCurves2.add(buttonSeven29);
		buttonSeven29.setBounds(406, 345, 80, 30);

		panelImage4.add(panelCurves2);
		panelCurves2.setBounds(0, 0, 490, 380);

		tabbedSelector21.addTab("", new javax.swing.ImageIcon(getClass()
				.getResource("/ISIS/Resource/ButtonImages/#4 (Copiar).png")),
				panelImage4, ""); // NOI18N
		panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ISIS/Resource/Backgrounds/BackCasas5.jpg"))); // NOI18N
		panelImage5.setLayout(null);

		panelCurves3.setLayout(null);

		jLabel21.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 5/lblcasino.png")));
		panelCurves3.add(jLabel21);
		jLabel21.setBounds(27, 12, 189, 100);

		buttonSeven21.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven21.setText("Comprar");
		buttonSeven21.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("casino");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});
		panelCurves3.add(buttonSeven21);
		buttonSeven21.setBounds(100, 100, 70, 22);

		jLabel22.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 5/lbldulceria.png")));
		panelCurves3.add(jLabel22);
		jLabel22.setBounds(30, 130, 189, 100);

		buttonSeven22.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven22.setText("Comprar");
		panelCurves3.add(buttonSeven22);
		buttonSeven22.setBounds(110, 220, 70, 22);
		buttonSeven22.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("dulceria");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel23.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 5/lblfabrica.png")));
		panelCurves3.add(jLabel23);
		jLabel23.setBounds(30, 260, 189, 100);

		buttonSeven23.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven23.setText("Comprar");
		panelCurves3.add(buttonSeven23);
		buttonSeven23.setBounds(110, 350, 70, 22);
		buttonSeven23.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("fabrica");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel24.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 5/lblheladeria.png")));
		panelCurves3.add(jLabel24);
		jLabel24.setBounds(220, 70, 189, 100);

		buttonSeven24.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven24.setText("Comprar");
		panelCurves3.add(buttonSeven24);
		buttonSeven24.setBounds(300, 160, 70, 22);
		buttonSeven24.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("heladeria");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		jLabel25.setIcon(new javax.swing.ImageIcon(
				ImageCache
						.getInstance()
						.getImage(
								"src/ISIS/Resource/MenuCompra/IndustriaComercio/Nivel 5/lblhotelEmpresarial.png")));
		panelCurves3.add(jLabel25);
		jLabel25.setBounds(220, 200, 189, 100);

		buttonSeven25.setBackground(new java.awt.Color(255, 0, 0));
		buttonSeven25.setText("Comprar");
		panelCurves3.add(buttonSeven25);
		buttonSeven25.setBounds(300, 290, 70, 22);
		buttonSeven25.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
				gamepanel.mouseClicked(evt);
				gamepanel.setClick(true);
				setSeleccionada("hotelEmpresarial");
				Mapa.objeto = new Construccion(getSeleccionada());
				Mapa.ESTADO = Estados.CONSTRUCCION;
				repaint();
			}
		});

		buttonSeven30.setBackground(new java.awt.Color(0, 0, 255));
		buttonSeven30.setText("Volver");
		buttonSeven30.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dispose();
			}
		});
		panelCurves3.add(buttonSeven30);
		buttonSeven30.setBounds(406, 345, 80, 30);

		panelImage5.add(panelCurves3);
		panelCurves3.setBounds(0, 0, 490, 380);

		tabbedSelector21.addTab("", new javax.swing.ImageIcon(getClass()
				.getResource("/ISIS/Resource/ButtonImages/#5 (Copiar).png")),
				panelImage5, ""); // NOI18N

		javax.swing.GroupLayout panelNice1Layout = new javax.swing.GroupLayout(
				panelNice1);
		panelNice1.setLayout(panelNice1Layout);
		panelNice1Layout
				.setHorizontalGroup(panelNice1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panelNice1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												tabbedSelector21,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												565, Short.MAX_VALUE)
										.addContainerGap()));
		panelNice1Layout.setVerticalGroup(panelNice1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				panelNice1Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(tabbedSelector21,
								javax.swing.GroupLayout.DEFAULT_SIZE, 397,
								Short.MAX_VALUE).addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 585, Short.MAX_VALUE)
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(panelNice1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										585, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 421, Short.MAX_VALUE)
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(panelNice1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										421, Short.MAX_VALUE)));

		if (gamepanel.habilitarNivel) {
			if (gamepanel.parametros.nivel == 1) {
				tabbedSelector21.setEnabledAt(1, false);
				tabbedSelector21.setEnabledAt(2, false);
				tabbedSelector21.setEnabledAt(3, false);
				tabbedSelector21.setEnabledAt(4, false);
			}

			if (gamepanel.parametros.nivel == 2) {
				tabbedSelector21.setEnabledAt(2, false);
				tabbedSelector21.setEnabledAt(3, false);
				tabbedSelector21.setEnabledAt(4, false);
			}

			if (gamepanel.parametros.nivel == 3) {
				tabbedSelector21.setEnabledAt(3, false);
				tabbedSelector21.setEnabledAt(4, false);
			}

			if (gamepanel.parametros.nivel == 4) {
				tabbedSelector21.setEnabledAt(4, false);
			}

		}
		pack();

	}// </editor-fold>//GEN-END:initComponents

	public void addActionListener(ActionListener listener) {
		eventListenerList.add(ActionListener.class, listener);
	}

	public void removeActionListener(ActionListener listener) {
		eventListenerList.remove(ActionListener.class, listener);
	}

	public ActionListener[] getActionListeners() {
		return eventListenerList.getListeners(ActionListener.class);
	}

	private void fireActionEvent(ActionEvent evt) {
		ActionListener[] actionListeners = getActionListeners();

		for (ActionListener actionListener : actionListeners) {
			actionListener.actionPerformed(evt);
		}
	}

	public static String getSeleccionada() {
		return seleccionada;
	}

	public static void setSeleccionada(String seleccionada) {
		DialogoIndustria.seleccionada = seleccionada;
	}

	public static Construccion getVivienda() {
		return vivienda;
	}

	public static void setVivienda(Construccion vivienda) {
		DialogoIndustria.vivienda = vivienda;
	}

	public static void main(String[] args) {
		JFrame frame = new JFrame();
		frame.setSize(800, 600);
		// frame.setVisible(true);
		DialogoIndustria dialogo = new DialogoIndustria(frame, false);
		dialogo.setVisible(true);
		dialogo.setLocationRelativeTo(frame);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private org.edisoncor.gui.button.ButtonSeven buttonComprar1;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven10;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven11;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven12;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven13;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven14;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven15;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven16;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven17;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven18;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven19;
	private org.edisoncor.gui.button.ButtonSeven buttonComprar2;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven20;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven21;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven22;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven23;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven24;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven25;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven26;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven27;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven28;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven29;
	private org.edisoncor.gui.button.ButtonSeven buttonComprar3;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven30;
	private org.edisoncor.gui.button.ButtonSeven buttonComprar4;
	private org.edisoncor.gui.button.ButtonSeven buttonComprar5;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven6;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven7;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven8;
	private org.edisoncor.gui.button.ButtonSeven buttonSeven9;
	private javax.swing.JLabel lblEdif1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel lblEdif2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel lblEdif3;
	private javax.swing.JLabel lblEdif4;
	private javax.swing.JLabel lblEdif5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private org.edisoncor.gui.panel.PanelCurves panelCurves1;
	private org.edisoncor.gui.panel.PanelCurves panelCurves2;
	private org.edisoncor.gui.panel.PanelCurves panelCurves3;
	private org.edisoncor.gui.panel.PanelCurves panelCurves4;
	private org.edisoncor.gui.panel.PanelCurves panelCurves5;
	private org.edisoncor.gui.panel.PanelImage panelImage1;
	private org.edisoncor.gui.panel.PanelImage panelImage2;
	private org.edisoncor.gui.panel.PanelImage panelImage3;
	private org.edisoncor.gui.panel.PanelImage panelImage4;
	private org.edisoncor.gui.panel.PanelImage panelImage5;
	private org.edisoncor.gui.panel.PanelNice panelNice1;
	private org.edisoncor.gui.tabbedPane.TabbedSelector2 tabbedSelector21;
	private EventListenerList eventListenerList = new EventListenerList();
	private Mapa gamepanel = new Mapa();
	static String seleccionada;
	private static Construccion vivienda;
	// End of variables declaration//GEN-END:variables
}
